name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ffrostfall/fluid

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.0

      - name: Log into Wally
        run: wally login --token "${{ secrets.WALLY_SECRET }}"

      - name: Upload to Wally
        run: wally publish
